CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

CREATE TABLE IF NOT EXISTS TitanicCSV (
  PassengerId INT,
  Survived VARCHAR(255),
  Pclass VARCHAR(255),
  Name VARCHAR(255),
  Sex VARCHAR(255),
  Age VARCHAR(255),
  SibSp VARCHAR(255),
  Parch VARCHAR(255),
  Ticket VARCHAR(255),
  Fare VARCHAR(255),
  Cabin VARCHAR(255),
  Embarked VARCHAR(255)
);
LOAD DATA INFILE '/var/lib/mysql-files/data.csv'
INTO TABLE TitanicCSV
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
